import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Dropzone from '../components/Dropzone.jsx'
import UrlInput from '../components/UrlInput.jsx'
import { uploadFile, submitUrl } from '../api/client.js'

const HOW_IT_WORKS = [
  {
    step: '1',
    title: 'Upload your episode',
    body: 'Drop an MP3/MP4 file or paste a YouTube link. Up to 500 MB, any length.',
  },
  {
    step: '2',
    title: 'AI extracts the gold',
    body: 'We transcribe, analyse themes and virality, and identify the best clips — automatically.',
  },
  {
    step: '3',
    title: 'Download your content pack',
    body: '5 vertical video clips, a full LinkedIn post, Twitter thread, show notes, newsletter, and 5 quote graphics — ready to publish.',
  },
]

const ARTIFACT_PILLS = [
  '5× vertical clips',
  'LinkedIn post',
  'Twitter thread',
  'Show notes',
  'Newsletter',
  'Quote graphics',
]

export default function LandingPage() {
  const navigate = useNavigate()
  const [uploadError, setUploadError] = useState('')
  const [uploading, setUploading] = useState(false)

  async function handleFile(file) {
    setUploadError('')
    setUploading(true)
    try {
      const { job_id } = await uploadFile(file)
      navigate(`/jobs/${job_id}`)
    } catch (err) {
      setUploadError(err.message ?? 'Upload failed. Please try again.')
      setUploading(false)
    }
  }

  async function handleUrl(url) {
    setUploadError('')
    const { job_id } = await submitUrl(url)
    navigate(`/jobs/${job_id}`)
  }

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* Hero */}
      <main>
        <section
          className="flex flex-col items-center justify-center gap-6 px-4 pt-16 sm:pt-24 pb-10 text-center"
          aria-labelledby="hero-heading"
        >
          <div
            className="inline-flex items-center gap-2 bg-indigo-50 text-indigo-700 text-xs font-semibold px-3 py-1 rounded-full uppercase tracking-wide"
            aria-hidden="true"
          >
            Hackathon MVP · AI-powered
          </div>

          <h1
            id="hero-heading"
            className="text-4xl sm:text-5xl font-extrabold text-gray-900 leading-tight max-w-2xl"
          >
            Turn your podcast into a{' '}
            <span className="text-indigo-600">full content pack</span>{' '}
            in 3 minutes
          </h1>

          <p className="text-base sm:text-lg text-gray-500 max-w-xl">
            Upload one audio or video file. Get{' '}
            <strong className="text-gray-700">10+ publish-ready assets</strong> — clips,
            posts, graphics — generated by AI.
          </p>

          {/* Artifact pills */}
          <ul className="flex flex-wrap justify-center gap-2 max-w-lg list-none" aria-label="Included assets">
            {ARTIFACT_PILLS.map((pill) => (
              <li
                key={pill}
                className="bg-gray-100 text-gray-600 text-xs font-medium px-3 py-1 rounded-full"
              >
                {pill}
              </li>
            ))}
          </ul>
        </section>

        {/* Upload section */}
        <section
          className="flex flex-col items-center gap-5 px-4 pb-16"
          aria-label="Upload your podcast"
        >
          {uploading ? (
            <div className="w-full max-w-xl flex flex-col items-center gap-3 py-10" role="status" aria-live="polite">
              <div
                className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin"
                aria-hidden="true"
              />
              <p className="text-sm text-gray-500">Uploading your episode…</p>
            </div>
          ) : (
            <Dropzone onFile={handleFile} />
          )}

          {uploadError && (
            <div role="alert" className="w-full max-w-xl bg-red-50 border border-red-200 rounded-xl px-4 py-3 flex flex-col sm:flex-row items-start sm:items-center gap-2">
              <p className="text-sm text-red-600 flex-1">{uploadError}</p>
              <button
                onClick={() => setUploadError('')}
                className="text-xs text-red-500 underline hover:text-red-700 shrink-0"
                aria-label="Dismiss error"
              >
                Try again
              </button>
            </div>
          )}

          <div className="flex items-center gap-3 w-full max-w-xl text-sm text-gray-400" role="separator" aria-hidden="true">
            <div className="flex-1 h-px bg-gray-200" />
            <span>or paste a YouTube URL</span>
            <div className="flex-1 h-px bg-gray-200" />
          </div>

          <UrlInput onSubmit={handleUrl} />
        </section>

        {/* How it works */}
        <section className="bg-gray-50 border-t border-gray-100 px-4 py-16" aria-labelledby="how-heading">
          <div className="max-w-4xl mx-auto">
            <h2 id="how-heading" className="text-2xl font-bold text-gray-900 text-center mb-10">
              How it works
            </h2>
            <ol className="grid grid-cols-1 sm:grid-cols-3 gap-8 list-none">
              {HOW_IT_WORKS.map(({ step, title, body }) => (
                <li key={step} className="flex flex-col items-center text-center gap-3">
                  <div
                    className="w-12 h-12 rounded-full bg-indigo-600 text-white text-xl font-bold flex items-center justify-center shrink-0"
                    aria-hidden="true"
                  >
                    {step}
                  </div>
                  <h3 className="font-semibold text-gray-900">{title}</h3>
                  <p className="text-sm text-gray-500 leading-relaxed">{body}</p>
                </li>
              ))}
            </ol>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-100 py-6 text-center text-xs text-gray-400">
        Podcast Pack · Hackathon MVP · Powered by Whisper + Claude
      </footer>
    </div>
  )
}
