import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Dropzone from '../components/Dropzone.jsx'
import UrlInput from '../components/UrlInput.jsx'
import { uploadFile, submitUrl } from '../api/client.js'

const HOW_IT_WORKS = [
  {
    step: '1',
    title: 'Upload your episode',
    body: 'Drop an MP3/MP4 file or paste a YouTube link. Up to 500 MB, any length.',
  },
  {
    step: '2',
    title: 'AI extracts the gold',
    body: 'We transcribe, analyse themes and virality, and identify the best clips — automatically.',
  },
  {
    step: '3',
    title: 'Download your content pack',
    body: '5 vertical video clips, a full LinkedIn post, Twitter thread, show notes, newsletter, and 5 quote graphics — ready to publish.',
  },
]

const ARTIFACT_PILLS = [
  '5× vertical clips',
  'LinkedIn post',
  'Twitter thread',
  'Show notes',
  'Newsletter',
  'Quote graphics',
]

export default function LandingPage() {
  const navigate = useNavigate()
  const [uploadError, setUploadError] = useState('')
  const [uploading, setUploading] = useState(false)

  async function handleFile(file) {
    setUploadError('')
    setUploading(true)
    try {
      const { job_id } = await uploadFile(file)
      navigate(`/jobs/${job_id}`)
    } catch (err) {
      setUploadError(err.message ?? 'Upload failed. Please try again.')
      setUploading(false)
    }
  }

  async function handleUrl(url) {
    setUploadError('')
    try {
      const { job_id } = await submitUrl(url)
      navigate(`/jobs/${job_id}`)
    } catch (err) {
      throw err
    }
  }

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* Hero */}
      <div className="flex flex-col items-center justify-center gap-6 px-4 pt-20 pb-12 text-center">
        <div className="inline-flex items-center gap-2 bg-indigo-50 text-indigo-700 text-xs font-semibold px-3 py-1 rounded-full uppercase tracking-wide">
          Hackathon MVP · AI-powered
        </div>

        <h1 className="text-5xl font-extrabold text-gray-900 leading-tight max-w-2xl">
          Turn your podcast into a{' '}
          <span className="text-indigo-600">full content pack</span>{' '}
          in 3 minutes
        </h1>

        <p className="text-lg text-gray-500 max-w-xl">
          Upload one audio or video file. Get{' '}
          <strong className="text-gray-700">10+ publish-ready assets</strong> — clips,
          posts, graphics — generated by AI.
        </p>

        {/* Artifact pills */}
        <div className="flex flex-wrap justify-center gap-2 max-w-lg">
          {ARTIFACT_PILLS.map((pill) => (
            <span
              key={pill}
              className="bg-gray-100 text-gray-600 text-xs font-medium px-3 py-1 rounded-full"
            >
              {pill}
            </span>
          ))}
        </div>
      </div>

      {/* Upload section */}
      <div className="flex flex-col items-center gap-5 px-4 pb-16">
        {uploading ? (
          <div className="w-full max-w-xl flex flex-col items-center gap-3 py-10">
            <div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
            <p className="text-sm text-gray-500">Uploading…</p>
          </div>
        ) : (
          <Dropzone onFile={handleFile} />
        )}

        {uploadError && (
          <p className="text-sm text-red-500 max-w-xl text-center" role="alert">
            {uploadError}
          </p>
        )}

        <div className="flex items-center gap-3 w-full max-w-xl text-sm text-gray-400">
          <div className="flex-1 h-px bg-gray-200" />
          <span>or paste a YouTube URL</span>
          <div className="flex-1 h-px bg-gray-200" />
        </div>

        <UrlInput onSubmit={handleUrl} />
      </div>

      {/* How it works */}
      <div className="bg-gray-50 border-t border-gray-100 px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl font-bold text-gray-900 text-center mb-10">
            How it works
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8">
            {HOW_IT_WORKS.map(({ step, title, body }) => (
              <div key={step} className="flex flex-col items-center text-center gap-3">
                <div className="w-12 h-12 rounded-full bg-indigo-600 text-white text-xl font-bold flex items-center justify-center shrink-0">
                  {step}
                </div>
                <h3 className="font-semibold text-gray-900">{title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{body}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="border-t border-gray-100 py-6 text-center text-xs text-gray-400">
        Podcast Pack · Hackathon MVP · Powered by Whisper + Claude
      </div>
    </div>
  )
}
