# Generated by Django 5.0.6 on 2026-04-23 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("INGESTING", "Ingesting"),
                            ("TRANSCRIBING", "Transcribing"),
                            ("ANALYZING", "Analyzing"),
                            ("GENERATING", "Generating"),
                            ("PACKAGING", "Packaging"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("file", "File"), ("url", "Url")], max_length=16
                    ),
                ),
                ("source_url", models.TextField(blank=True, null=True)),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("raw_media_path", models.TextField(blank=True, null=True)),
                ("normalized_wav_path", models.TextField(blank=True, null=True)),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=64, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "jobs",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="jobs_status_24a2b0_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="jobs_created_91fc39_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("episode_title", models.CharField(max_length=255)),
                ("hook", models.TextField()),
                ("guest_json", models.JSONField(blank=True, null=True)),
                ("themes_json", models.JSONField(default=list)),
                ("chapters_json", models.JSONField(default=list)),
                ("clip_candidates_json", models.JSONField(default=list)),
                ("quotes_json", models.JSONField(default=list)),
                ("claude_model", models.CharField(max_length=64)),
                ("input_tokens", models.IntegerField()),
                ("output_tokens", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="models.job",
                    ),
                ),
            ],
            options={
                "db_table": "analyses",
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=8)),
                ("full_text", models.TextField()),
                ("segments_json", models.JSONField(default=list)),
                ("whisper_model", models.CharField(default="whisper-1", max_length=32)),
                ("duration_sec", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="models.job",
                    ),
                ),
            ],
            options={
                "db_table": "transcripts",
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VIDEO_CLIP", "Video Clip"),
                            ("LINKEDIN_POST", "Linkedin Post"),
                            ("TWITTER_THREAD", "Twitter Thread"),
                            ("SHOW_NOTES", "Show Notes"),
                            ("NEWSLETTER", "Newsletter"),
                            ("QUOTE_GRAPHIC", "Quote Graphic"),
                            ("EPISODE_THUMBNAIL", "Episode Thumbnail"),
                            ("YOUTUBE_DESCRIPTION", "Youtube Description"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("index", models.IntegerField()),
                ("file_path", models.TextField(blank=True, null=True)),
                ("text_content", models.TextField(blank=True, null=True)),
                ("metadata_json", models.JSONField(default=dict)),
                ("version", models.IntegerField(default=1)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="models.job",
                    ),
                ),
            ],
            options={
                "db_table": "artifacts",
                "indexes": [
                    models.Index(
                        fields=["job", "status"], name="artifacts_job_id_f241ed_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.UniqueConstraint(
                fields=("job", "type", "index"), name="uniq_artifact_job_type_index"
            ),
        ),
    ]
