# Generated by Django 5.0.6 on 2026-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_package_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('VIDEO_CLIP', 'Video Clip'), ('LINKEDIN_POST', 'Linkedin Post'), ('TWITTER_THREAD', 'Twitter Thread'), ('SHOW_NOTES', 'Show Notes'), ('NEWSLETTER', 'Newsletter'), ('QUOTE_GRAPHIC', 'Quote Graphic'), ('EPISODE_THUMBNAIL', 'Episode Thumbnail'), ('YOUTUBE_DESCRIPTION', 'Youtube Description'), ('TRANSCRIPT', 'Transcript')], max_length=32),
        ),
    ]
