# Generated by Django 5.0.6 on 2026-09-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_artifact_type_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='brand_color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='job',
            name='logo_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='podcast_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
