# Generated by Django 5.0.6 on 2026-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='caption_style',
            field=models.CharField(default='karaoke', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='clip_layout',
            field=models.CharField(default='pad', max_length=8),
        ),
    ]
